services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    args:
      DATABASE_URL: postgresql://root:root@localhost:5432/vashaoptika
      JWT_SECRET: abvgde
      HASH_SECRET: abvgd
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    container_name: postgres
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:

