services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://root:root@192.168.0.25:5432/vashaoptika
      JWT_SECRET: abvgde
      HASH_SECRET: abvgd
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    container_name: postgres
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    ports:
      - "50080:80"
      - "50443:443"
    volumes:
      - /var/www/html:/usr/share/nginx/html
    restart: always
volumes:
  postgres-data:

